from . import sale_margin
from . import sale_margin_per_apply
from . import sale_order_recalculate
from . import account_invoice_margin
from . import account_invoice_line_margin
from . import ordenes_reparacion
from . import taller_margin
from . import refacciones_ordenes_de_reparacion_recalculate
from . import ordenes_de_reparacion_recalculate